In [1]:
import pandas as pd

In [22]:
df  = pd.read_csv(r"D:\Spoter_transformer_SLR\datasets\LSA64_60fps.csv")
df

middlePIP_left_Y  \
0     [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...   
1     [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...   
2     [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...   
3     [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...   
4     [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...   
...                                                 ...   
3172  [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.645152,0,0,0,...   
3173  [0.745047,0.746021,0.74954,0.749973,0.744611,0...   
3174  [0.756741,0.759231,0.760493,0.757967,0.760987,...   
3175  [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...   
3176  [0.766391,0.770084,0.772836,0.757491,0.769122,...   

                                      littlePIP_right_Y  \
0     [0.480768,0.539875,0.539875,0.528246,0.385103,...   
1     [0.403426,0.403426,0.329711,0.27934,0.23615,0....   
2     [0.369301,0.346545,0.300266,0.27501,0.403454,0...   
3     [0.347376,0.297279,0.227626,0.196653,0.175164,...   
4     [0.513722,0.454096,0.384418,0.474525,0.513722,...   
...                                                 ...   
3172  [0.639119,0.639119,0.641245,0.645053,0.647711,...   
3173  [0.587882,0.591506,0.588626,0.598531,0.611406,...   
3174  [0.613927,0.613561,0.612129,0.612954,0.615535,...   
3175  [0.555635,0.55881,0.557885,0.555253,0.555472,0...   
3176  [0.599623,0.613396,0.61819,0.640182,0.623187,0...   

                                      middleTip_right_Y  \
0     [0.519275,0.57261,0.57261,0.561763,0.437387,0....   
1     [0.460311,0.460311,0.401397,0.344263,0.290415,...   
2     [0.424287,0.404329,0.370551,0.345217,0.452219,...   
3     [0.410467,0.372986,0.28378,0.222777,0.165774,0...   
4     [0.548968,0.499755,0.435891,0.523084,0.548968,...   
...                                                 ...   
3172  [0.664347,0.664347,0.677828,0.695074,0.688065,...   
3173  [0.595657,0.596863,0.595192,0.60741,0.626243,0...   
3174  [0.610008,0.607465,0.60909,0.608302,0.613609,0...   
3175  [0.63351,0.639603,0.640625,0.58462,0.642912,0....   
3176  [0.591921,0.617219,0.632836,0.669475,0.654291,...   

                                         thumbIP_left_X  \
0     [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...   
1     [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...   
2     [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...   
3     [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...   
4     [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...   
...                                                 ...   
3172  [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.518995,0,0,0,...   
3173  [0.703993,0.705711,0.657824,0.660637,0.684466,...   
3174  [0.654385,0.652712,0.651633,0.659783,0.652565,...   
3175  [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...   
3176  [0.708226,0.636223,0,0.670208,0.705147,0.70452...   

                                      middleMCP_right_Y  \
0     [0.520391,0.588775,0.588775,0.573419,0.45349,0...   
1     [0.45883,0.45883,0.404698,0.364033,0.314743,0....   
2     [0.424357,0.402919,0.372459,0.35448,0.452747,0...   
3     [0.413966,0.373953,0.312884,0.273416,0.243723,...   
4     [0.564088,0.50523,0.446888,0.535751,0.564088,0...   
...                                                 ...   
3172  [0.624796,0.624796,0.631184,0.632833,0.635476,...   
3173  [0.601897,0.603231,0.602674,0.60925,0.614825,0...   
3174  [0.624193,0.623393,0.623107,0.623051,0.624582,...   
3175  [0.571778,0.575358,0.571143,0.557236,0.574017,...   
3176  [0.606643,0.617886,0.621004,0.630512,0.624708,...   

                                       indexMCP_right_X  \
0     [0.438436,0.42064,0.42064,0.422754,0.451421,0....   
1     [0.39455,0.39455,0.399423,0.402916,0.405791,0....   
2     [0.413969,0.414996,0.420176,0.426308,0.403637,...   
3     [0.412881,0.418208,0.414228,0.415017,0.415217,...   
4     [0.414915,0.42389,0.433532,0.424029,0.414915,0...   
...                                                 ...   
3172  [0.333275,0.333275,0.340778,0.358339,0.351185,...   
3173  [0.472818,0.4748

In [21]:
num_other_features = 0
for column_name in df.columns:
    if column_name.split("_")[-1] != "X" and column_name.split("_")[-1] != "Y":
        num_other_features += 1
num_other_features

4

In [1]:
import torch
import torch.nn as nn

In [45]:
row_embed = nn.Parameter(torch.rand(1, 108))
print(row_embed.shape)
# print(row_embed[0])
print(row_embed[0].shape)
# print(row_embed[0].unsqueeze(0))
print(row_embed[0].unsqueeze(0).shape)
# print(row_embed[0].unsqueeze(0).repeat(1,1,1))
print(row_embed[0].unsqueeze(0).repeat(1,1,1).shape)
# print(torch.cat([row_embed[0].unsqueeze(0).repeat(1, 1, 1)], dim=-1))
print(torch.cat([row_embed[0].unsqueeze(0).repeat(1, 1, 1)], dim=-1).shape)
print(torch.cat([row_embed[0].unsqueeze(0).repeat(1, 1, 1)], dim=-1).flatten(0,1).shape)
print(torch.cat([row_embed[0].unsqueeze(0).repeat(1, 1, 1)], dim=-1).flatten(0,1).unsqueeze(0).shape)
pos = torch.cat([row_embed[0].unsqueeze(0).repeat(1, 1, 1)], dim=-1).flatten(0,1).unsqueeze(0)
pos

torch.Size([1, 108])
torch.Size([108])
torch.Size([1, 108])
torch.Size([1, 1, 108])
torch.Size([1, 1, 108])
torch.Size([1, 108])
torch.Size([1, 1, 108])


tensor([[[0.4809, 0.2101, 0.2408, 0.6648, 0.1788, 0.0533, 0.2906, 0.7263,
          0.3181, 0.1913, 0.7200, 0.9317, 0.8394, 0.2394, 0.4916, 0.2415,
          0.6768, 0.7861, 0.8663, 0.1291, 0.8308, 0.7676, 0.2384, 0.1894,
          0.8818, 0.4383, 0.4926, 0.7020, 0.1645, 0.2892, 0.7186, 0.6023,
          0.6809, 0.0606, 0.3875, 0.0297, 0.5826, 0.8992, 0.8136, 0.0789,
          0.0168, 0.6483, 0.6990, 0.1962, 0.5912, 0.1652, 0.6527, 0.2566,
          0.0808, 0.3330, 0.8749, 0.7552, 0.9801, 0.4786, 0.3839, 0.6337,
          0.1014, 0.2276, 0.9813, 0.1962, 0.4975, 0.9336, 0.0036, 0.1103,
          0.1885, 0.1685, 0.8273, 0.7426, 0.4535, 0.4938, 0.0641, 0.5413,
          0.3712, 0.4997, 0.2934, 0.5090, 0.6460, 0.3764, 0.3029, 0.6059,
          0.5731, 0.4311, 0.1391, 0.0623, 0.6014, 0.9731, 0.0166, 0.3123,
          0.5525, 0.2806, 0.7222, 0.1192, 0.4235, 0.7639, 0.4052, 0.3857,
          0.1478, 0.8109, 0.0647, 0.9365, 0.4681, 0.4267, 0.1828, 0.5951,
          0.2989, 0.4173, 0.4435, 0.38

In [131]:
print([row_embed[0].unsqueeze(0).repeat(1,1,1)])

print(torch.cat([row_embed[0].unsqueeze(0).repeat(1,1,1)], dim=-1))


[tensor([[[0.4400, 0.4622, 0.5543]]], grad_fn=<RepeatBackward>)]
tensor([[[0.4400, 0.4622, 0.5543]]], grad_fn=<CatBackward>)


In [136]:
torch.cat([row_embed[0].unsqueeze(0).repeat(1, 1, 1)], dim=-1).flatten(0, 1)

tensor([[0.4400, 0.4622, 0.5543]], grad_fn=<ViewBackward>)

In [83]:
video = torch.rand(60, 54, 2)
print("video: " + str(video.shape))
video_flatten = video.flatten(start_dim=1)
print("video_flatten: " + str(video_flatten.shape))
video_unsqeeze = torch.unsqueeze(video_flatten, 1)
print("video_unsqeeze: " + str(video_flatten.shape))

# video_unsqeeze.shape
h = pos + video_flatten 
print("h.shape: " + str(h.shape))

h

video: torch.Size([60, 54, 2])
video_flatten: torch.Size([60, 108])
video_unsqeeze: torch.Size([60, 108])
h.shape: torch.Size([1, 60, 108])


tensor([[[0.9411, 0.3416, 0.6625,  ..., 0.8021, 0.9164, 1.2620],
         [0.9613, 0.7125, 1.0813,  ..., 1.1823, 0.5856, 0.4749],
         [0.9673, 1.0008, 1.1407,  ..., 1.0348, 0.5973, 1.1624],
         ...,
         [0.9271, 0.7154, 1.0481,  ..., 0.7573, 0.5926, 0.9995],
         [0.8014, 0.8772, 0.3278,  ..., 1.3703, 1.3574, 0.4932],
         [1.3016, 0.5641, 1.0476,  ..., 0.8554, 0.6350, 0.8333]]],
       grad_fn=<AddBackward0>)

In [151]:
import math
def get_positional_encoding(seq_len, hidden_dim):
    position = torch.arange(seq_len, dtype=torch.float).unsqueeze(1)
    div_term = torch.exp(torch.arange(0, hidden_dim, 2).float() * (-math.log(10000.0) / hidden_dim))
    positional_encoding = torch.zeros((seq_len, hidden_dim))

    positional_encoding[:, 0::2] = torch.sin(position * div_term)
    positional_encoding[:, 1::2] = torch.cos(position * div_term)

    return positional_encoding

x  = get_positional_encoding(54, 2)
print(x)

tensor([[ 0.0000,  1.0000],
        [ 0.8415,  0.5403],
        [ 0.9093, -0.4161],
        [ 0.1411, -0.9900],
        [-0.7568, -0.6536],
        [-0.9589,  0.2837],
        [-0.2794,  0.9602],
        [ 0.6570,  0.7539],
        [ 0.9894, -0.1455],
        [ 0.4121, -0.9111],
        [-0.5440, -0.8391],
        [-1.0000,  0.0044],
        [-0.5366,  0.8439],
        [ 0.4202,  0.9074],
        [ 0.9906,  0.1367],
        [ 0.6503, -0.7597],
        [-0.2879, -0.9577],
        [-0.9614, -0.2752],
        [-0.7510,  0.6603],
        [ 0.1499,  0.9887],
        [ 0.9129,  0.4081],
        [ 0.8367, -0.5477],
        [-0.0089, -1.0000],
        [-0.8462, -0.5328],
        [-0.9056,  0.4242],
        [-0.1324,  0.9912],
        [ 0.7626,  0.6469],
        [ 0.9564, -0.2921],
        [ 0.2709, -0.9626],
        [-0.6636, -0.7481],
        [-0.9880,  0.1543],
        [-0.4040,  0.9147],
        [ 0.5514,  0.8342],
        [ 0.9999, -0.0133],
        [ 0.5291, -0.8486],
        [-0.4282, -0

In [152]:
torch.arange(54, dtype=torch.float).unsqueeze(1)


tensor([[ 0.],
        [ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.],
        [11.],
        [12.],
        [13.],
        [14.],
        [15.],
        [16.],
        [17.],
        [18.],
        [19.],
        [20.],
        [21.],
        [22.],
        [23.],
        [24.],
        [25.],
        [26.],
        [27.],
        [28.],
        [29.],
        [30.],
        [31.],
        [32.],
        [33.],
        [34.],
        [35.],
        [36.],
        [37.],
        [38.],
        [39.],
        [40.],
        [41.],
        [42.],
        [43.],
        [44.],
        [45.],
        [46.],
        [47.],
        [48.],
        [49.],
        [50.],
        [51.],
        [52.],
        [53.]])

In [145]:
new = x.flatten(0, 1).unsqueeze(0).unsqueeze(0)
print(new)
new.shape

tensor([[[ 0.0000,  1.0000,  0.8415,  0.5403,  0.9093, -0.4161,  0.1411,
          -0.9900, -0.7568, -0.6536, -0.9589,  0.2837, -0.2794,  0.9602,
           0.6570,  0.7539,  0.9894, -0.1455,  0.4121, -0.9111, -0.5440,
          -0.8391, -1.0000,  0.0044, -0.5366,  0.8439,  0.4202,  0.9074,
           0.9906,  0.1367,  0.6503, -0.7597, -0.2879, -0.9577, -0.9614,
          -0.2752, -0.7510,  0.6603,  0.1499,  0.9887,  0.9129,  0.4081,
           0.8367, -0.5477, -0.0089, -1.0000, -0.8462, -0.5328, -0.9056,
           0.4242, -0.1324,  0.9912,  0.7626,  0.6469,  0.9564, -0.2921,
           0.2709, -0.9626, -0.6636, -0.7481, -0.9880,  0.1543, -0.4040,
           0.9147,  0.5514,  0.8342,  0.9999, -0.0133,  0.5291, -0.8486,
          -0.4282, -0.9037, -0.9918, -0.1280, -0.6435,  0.7654,  0.2964,
           0.9551,  0.9638,  0.2666,  0.7451, -0.6669, -0.1586, -0.9873,
          -0.9165, -0.4000, -0.8318,  0.5551,  0.0177,  0.9998,  0.8509,
           0.5253,  0.9018, -0.4322,  0.1236, -0.99

torch.Size([1, 1, 108])

In [29]:
position = torch.arange(1, dtype=torch.float).unsqueeze(1)
position

tensor([[0.]])

In [48]:
import numpy as np
import matplotlib.pyplot as plt

def getPositionEncoding(seq_len, d, n=10000):
    P = np.zeros((seq_len, d))
    for k in range(seq_len):
        for i in np.arange(int(d/2)):
            denominator = np.power(n, 2*i/d)
            P[k, 2*i] = np.sin(k/denominator)
            P[k, 2*i+1] = np.cos(k/denominator)
    return P

P = getPositionEncoding(seq_len=50, d=108, n=100)
print(P)
print(P.shape)

[[ 0.          1.          0.         ...  1.          0.
   1.        ]
 [ 0.84147098  0.54030231  0.79454282 ...  0.99992967  0.01089001
   0.9999407 ]
 [ 0.90929743 -0.41614684  0.96490571 ...  0.99971871  0.02177874
   0.99976282]
 ...
 [ 0.12357312 -0.99233547 -0.73410373 ...  0.84862996  0.48978296
   0.8718444 ]
 [-0.76825466 -0.64014434  0.0937705  ...  0.84229679  0.49924832
   0.86645895]
 [-0.95375265  0.30059254  0.84798014 ...  0.83584516  0.50865446
   0.86097075]]
(50, 108)


In [53]:
new_P = P + P
new_P.shape

(50, 108)

In [90]:
pos  = torch.arange(108).unsqueeze(0).unsqueeze(0)
print(pos)
print(pos.shape)

tensor([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
           14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
           28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
           42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
           56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
           70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
           84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
           98,  99, 100, 101, 102, 103, 104, 105, 106, 107]]])
torch.Size([1, 1, 108])


In [91]:
one_video  = torch.arange(108).unsqueeze(0).repeat(8,1)
print(one_video)
print(one_video.shape)

tensor([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
          14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
          28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
          42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
          56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
          70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
          84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
          98,  99, 100, 101, 102, 103, 104, 105, 106, 107],
        [  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
          14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
          28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
          42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
          56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  6

In [94]:
new = one_video + pos
print(new)
new.shape

tensor([[[  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
           28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,  54,
           56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,
           84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104, 106, 108, 110,
          112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138,
          140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166,
          168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194,
          196, 198, 200, 202, 204, 206, 208, 210, 212, 214],
         [  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
           28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,  54,
           56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,
           84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104, 106, 108, 110,
          112, 114, 116, 118, 120, 122, 124, 126, 128, 130,

torch.Size([1, 8, 108])